variables:
  - name: projectName
    value: Test Project Name
  - name: testTag
    value: Tag12345
scripts:
  Windows: 
    - ""
  Linux: 
    - ""
  MacOS: 
    - ""
  All: 
    - "echo Let's create"